# Quaternion from camera to IMU frame
qw: 0.0
qx: 1.0
qy: 0.0
qz: 0.0

# Translation from camera to IMU frame
Translation: [0.0,0.0,0.0]

# Rotation matrix from camera to IMU frame
Rotation: [1.0, 0.0, 0.0,
           0.0, 0.0,-1.0, 
           0.0, 1.0, 0.0]

