#################
# IMU PARAMETER #
#################

# Note: Noise parameters have to be defined in CONTINUOUS-TIME here.

/multicopter_unity_sim/imu/accelerometer_noise_density: 1.86e-3
/multicopter_unity_sim/imu/gyroscope_noise_density: 1.87e-4
/multicopter_unity_sim/imu/accelerometer_random_walk: 4.33e-4
/multicopter_unity_sim/imu/gyroscope_random_walk: 2.66e-5
